server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 1800

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeonlimgeol@gmail.com
    password: qlj311!@#$
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  security:
    user:
      name: test
      password: 1234
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:mariadb://localhost:3306/db_myblog
      driver-class-name: org.mariadb.jdbc.Driver
      username: user_blog
      password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always

file:
  path: C:\Users\quanl\upload

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG
